export const enum StoreActions {
  SET_ALIGNMENT         = 'SET_ALIGNMENT',
  ADD_ALIGNMENT_PARAMS  = 'ADD_ALIGNMENT_PARAMS',
  ADD_CLUSTERING_PARAMS = 'ADD_CLUSTERING_PARAMS',
  ADD_GLOBAL_PLOTS      = 'ADD_GLOBAL_PLOTS',
  UPDATE_GLOBAL_PLOTS   = 'UPDATE_GLOBAL_PLOTS',
  ADD_LOCAL_PLOTS       = 'ADD_LOCAL_PLOTS',
  ADD_MACRO_TRACKS      = 'ADD_MACRO_TRACKS',
  ADD_MICRO_TRACKS      = 'ADD_MICRO_TRACKS',
  SET_ORDER             = 'SET_ORDER',
  SET_REGEXP            = 'SET_REGEXP',
  SELECT_PLOT           = 'SELECT_PLOT',
  ADD_QUERY_PARAMS      = 'ADD_QUERY_PARAMS'
}
