# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genesearch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='genesearch.proto',
  package='genesearch',
  syntax='proto3',
  serialized_options=b'\n\022lis.gcv.genesearchB\017GeneSearchProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10genesearch.proto\x12\ngenesearch\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1c\n\x0bSearchReply\x12\r\n\x05genes\x18\x01 \x03(\t2L\n\nGeneSearch\x12>\n\x06Search\x12\x19.genesearch.SearchRequest\x1a\x17.genesearch.SearchReply\"\x00\x42,\n\x12lis.gcv.genesearchB\x0fGeneSearchProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='genesearch.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='genesearch.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='genesearch.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='genes', full_name='genesearch.SearchReply.genes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'genesearch_pb2'
  # @@protoc_insertion_point(class_scope:genesearch.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'genesearch_pb2'
  # @@protoc_insertion_point(class_scope:genesearch.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)


DESCRIPTOR._options = None

_GENESEARCH = _descriptor.ServiceDescriptor(
  name='GeneSearch',
  full_name='genesearch.GeneSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='genesearch.GeneSearch.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENESEARCH)

DESCRIPTOR.services_by_name['GeneSearch'] = _GENESEARCH

# @@protoc_insertion_point(module_scope)
