# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chromosomeregion_pb2 as chromosomeregion__pb2


class ChromosomeRegionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRegion = channel.unary_unary(
                '/chromosomeregion.ChromosomeRegion/GetRegion',
                request_serializer=chromosomeregion__pb2.RegionRequest.SerializeToString,
                response_deserializer=chromosomeregion__pb2.RegionReply.FromString,
                )


class ChromosomeRegionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRegion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChromosomeRegionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegion,
                    request_deserializer=chromosomeregion__pb2.RegionRequest.FromString,
                    response_serializer=chromosomeregion__pb2.RegionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chromosomeregion.ChromosomeRegion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChromosomeRegion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chromosomeregion.ChromosomeRegion/GetRegion',
            chromosomeregion__pb2.RegionRequest.SerializeToString,
            chromosomeregion__pb2.RegionReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
