# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromosomeregion.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromosomeregion.proto',
  package='chromosomeregion',
  syntax='proto3',
  serialized_options=b'\n\030lis.gcv.chromosomeregionB\025ChromosomeRegionProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63hromosomeregion.proto\x12\x10\x63hromosomeregion\"@\n\rRegionRequest\x12\x12\n\nchromosome\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0c\n\x04stop\x18\x03 \x01(\r\".\n\x0bRegionReply\x12\x0c\n\x04gene\x18\x01 \x01(\t\x12\x11\n\tneighbors\x18\x02 \x01(\x05\x32\x61\n\x10\x43hromosomeRegion\x12M\n\tGetRegion\x12\x1f.chromosomeregion.RegionRequest\x1a\x1d.chromosomeregion.RegionReply\"\x00\x42\x38\n\x18lis.gcv.chromosomeregionB\x15\x43hromosomeRegionProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_REGIONREQUEST = _descriptor.Descriptor(
  name='RegionRequest',
  full_name='chromosomeregion.RegionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='chromosomeregion.RegionRequest.chromosome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='chromosomeregion.RegionRequest.start', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop', full_name='chromosomeregion.RegionRequest.stop', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=108,
)


_REGIONREPLY = _descriptor.Descriptor(
  name='RegionReply',
  full_name='chromosomeregion.RegionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gene', full_name='chromosomeregion.RegionReply.gene', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='chromosomeregion.RegionReply.neighbors', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['RegionRequest'] = _REGIONREQUEST
DESCRIPTOR.message_types_by_name['RegionReply'] = _REGIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegionRequest = _reflection.GeneratedProtocolMessageType('RegionRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREQUEST,
  '__module__' : 'chromosomeregion_pb2'
  # @@protoc_insertion_point(class_scope:chromosomeregion.RegionRequest)
  })
_sym_db.RegisterMessage(RegionRequest)

RegionReply = _reflection.GeneratedProtocolMessageType('RegionReply', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREPLY,
  '__module__' : 'chromosomeregion_pb2'
  # @@protoc_insertion_point(class_scope:chromosomeregion.RegionReply)
  })
_sym_db.RegisterMessage(RegionReply)


DESCRIPTOR._options = None

_CHROMOSOMEREGION = _descriptor.ServiceDescriptor(
  name='ChromosomeRegion',
  full_name='chromosomeregion.ChromosomeRegion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=255,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRegion',
    full_name='chromosomeregion.ChromosomeRegion.GetRegion',
    index=0,
    containing_service=None,
    input_type=_REGIONREQUEST,
    output_type=_REGIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHROMOSOMEREGION)

DESCRIPTOR.services_by_name['ChromosomeRegion'] = _CHROMOSOMEREGION

# @@protoc_insertion_point(module_scope)
