# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromosomesearch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromosomesearch.proto',
  package='chromosomesearch',
  syntax='proto3',
  serialized_options=b'\n\030lis.gcv.chromosomesearchB\025ChromosomeSearchProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63hromosomesearch.proto\x12\x10\x63hromosomesearch\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\x0bSearchReply\x12\x13\n\x0b\x63hromosomes\x18\x01 \x03(\t2^\n\x10\x43hromosomeSearch\x12J\n\x06Search\x12\x1f.chromosomesearch.SearchRequest\x1a\x1d.chromosomesearch.SearchReply\"\x00\x42\x38\n\x18lis.gcv.chromosomesearchB\x15\x43hromosomeSearchProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='chromosomesearch.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='chromosomesearch.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=74,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='chromosomesearch.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosomes', full_name='chromosomesearch.SearchReply.chromosomes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'chromosomesearch_pb2'
  # @@protoc_insertion_point(class_scope:chromosomesearch.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'chromosomesearch_pb2'
  # @@protoc_insertion_point(class_scope:chromosomesearch.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)


DESCRIPTOR._options = None

_CHROMOSOMESEARCH = _descriptor.ServiceDescriptor(
  name='ChromosomeSearch',
  full_name='chromosomesearch.ChromosomeSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=206,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='chromosomesearch.ChromosomeSearch.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHROMOSOMESEARCH)

DESCRIPTOR.services_by_name['ChromosomeSearch'] = _CHROMOSOMESEARCH

# @@protoc_insertion_point(module_scope)
