export const enum StoreActions {
  // alignment actions
  UPDATE_ALIGNMENT_PARAMS  = 'UPDATE_ALIGNMENT_PARAMS',
  NEW_ALIGNED_TRACKS       = 'NEW_ALIGNED_TRACKS',
  // micro track actions
  UPDATE_QUERY_PARAMS      = 'UPDATE_QUERY_PARAMS',
  NEW_SEARCH_QUERY_TRACK   = 'NEW_SEARCH_QUERY_TRACK',
  // macro track actions
  UPDATE_BLOCK_PARAMS      = 'UPDATE_BLOCK_PARAMS',
  NEW_MACRO_CHROMOSOME     = 'NEW_MACRO_CHROMOSOME',
  // url actions
  ADD_URL_QUERY_PARAMS     = 'ADD_URL_QUERY_PARAMS',
  NEW_MULTI_QUERY_GENES    = 'NEW_MULTI_QUERY_GENES',
  NEW_SEARCH_QUERY_GENE    = 'NEW_SEARCH_QUERY_GENE',
  NEW_ROUTE                = 'NEW_ROUTE',
  // clustering actions
  UPDATE_CLUSTERING_PARAMS = 'UPDATE_CLUSTERING_PARAMS',
  NEW_CLUSTERED_TRACKS     = 'NEW_CLUSTERED_TRACKS',

  RESET                 = 'RESET',
  SET_ALIGNMENT         = 'SET_ALIGNMENT',
  ADD_GLOBAL_PLOTS      = 'ADD_GLOBAL_PLOTS',
  UPDATE_GLOBAL_PLOTS   = 'UPDATE_GLOBAL_PLOTS',
  ADD_LOCAL_PLOTS       = 'ADD_LOCAL_PLOTS',
  ADD_MACRO_TRACKS      = 'ADD_MACRO_TRACKS',
  ADD_MICRO_TRACKS      = 'ADD_MICRO_TRACKS',
  SET_ORDER             = 'SET_ORDER',
  SET_REGEXP            = 'SET_REGEXP',
  SELECT_PLOT           = 'SELECT_PLOT'
}
